### ISSUE TITLE
Space between label and the chart when position is 'Outside'

### ISSUE THREAD

**Issue by fannyfrey** [emn178/Chart.PieceLabel.js#54]
Hello, I tried adding outsidePadding which I assumed was to add space between label and the chart, but what it adds padding on the canvas instead. 

Here's what I got initially.

<img width="469" alt="screen shot 2018-05-01 at 15 28 25" src="https://user-images.githubusercontent.com/22318292/39466913-7cacba8a-4d55-11e8-84c9-f52f8baddeaa.png">

Upon adding outsidePadding
<img width="564" alt="screen shot 2018-05-01 at 15 37 12" src="https://user-images.githubusercontent.com/22318292/39466930-9766c0e6-4d55-11e8-8a07-1f0600652d9f.png">

**Comment by sunweiyang** [comment]
Looks like the was working with PR #46 (before `pieceLabel.padding` was renamed to `pieceLabel.outsidePadding` in @emn178's 45d406be908855c26f9ff643332dee424dbc685e. 

It looks like this issue was introduced in the above commit when in line 100,
```
var rangeFromCentre, offset = this.fontSize + this.padding
```
was replaced with
```
var rangeFromCentre, offset = this.fontSize + 2
```

I believe the correct version of this line should be:
```
var rangeFromCentre, offset = this.fontSize + this.outsidePadding
```

@emn178, can you confirm? Thanks for a fantastic plugin!

**Comment by emn178** [comment]
v0.11.0 add a new option textMargin for this. please try it.

**Comment by sunweiyang** [comment]
Looks like this new prop solves the issue, thanks @emn178!
